# Sử dụng base image cho runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Sử dụng SDK image để build code
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy file project và restore các thư viện (NuGet)
COPY ["giangminhnhat_2123110244.csproj", "."]
RUN dotnet restore "./giangminhnhat_2123110244.csproj"

# Copy toàn bộ code còn lại vào và build
COPY . .
RUN dotnet build "giangminhnhat_2123110244.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "giangminhnhat_2123110244.csproj" -c Release -o /app/publish /p:UseAppHost=false

# Bước cuối cùng: Chạy ứng dụng
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENV ASPNETCORE_URLS=http://+:80
ENTRYPOINT ["dotnet", "giangminhnhat_2123110244.dll"]